---
# Variable configuration.
- name: Include OS-specific variables (Debian stable)
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian' and ansible_distribution_version != 'buster/sid'

- name: Include OS-specific variables (Debian testing)
  include_vars: "{{ ansible_distribution }}-10.yml"
  when: ansible_os_family == 'Debian' and ansible_distribution_version == 'buster/sid'

- name: Define plantd_broker_packages
  set_fact:
    plantd_broker_packages: "{{ __plantd_broker_packages | list }}"
  when: plantd_broker_packages is not defined

- name: Define plantd_broker_version
  set_fact:
    plantd_broker_version: "{{ __plantd_broker_version }}"
  when: plantd_broker_version is not defined

- name: Define plantd_broker_daemon
  set_fact:
    plantd_broker_daemon: "{{ __plantd_broker_daemon }}"
  when: plantd_broker_daemon is not defined
